version: "3.5"
services:
  frontend:
    build: .
    ports:
     - "5000:5000"
    networks:
      mmm-network:
    environment:
      NEO4J_USER: ${NEO4J_USER}
      NEO4J_PSWD: ${NEO4J_PSWD}
  neo4j:
    image: "neo4j:latest"
    ports:
     - "7474:7474"
     - "7687:7687"
    networks:
      mmm-network:
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PSWD}

networks:
  mmm-network:
